# This is a basic workflow to help you get started with Actions

name: Project3

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6 
      
      - name: Install dependencies
        run: |
          pip install .
          pip install -r requirements.txt
      - name: Run unit tests
        run: 
          python -m pytest -v
